package view;

import controller.ControllerAnimal;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Animal;

/**
 *
 * @author Pc do Rik
 */
public class CadastroAnimal extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAnimal
     */
    public CadastroAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_idAnimal = new javax.swing.JLabel();
        Label_NomeAnimal = new javax.swing.JLabel();
        Label_RacaAnimal = new javax.swing.JLabel();
        IDCadastroAnimal = new javax.swing.JTextField();
        NomeCadastroAnimal = new javax.swing.JTextField();
        RacaCadastroAnimal = new javax.swing.JTextField();
        Label_TipoAnimal = new javax.swing.JLabel();
        Label_NascAnimal = new javax.swing.JLabel();
        Nasc_CadastroAnimal = new javax.swing.JFormattedTextField();
        SalvarCadastroAnimal = new javax.swing.JButton();
        Combo_TipoAnimal = new javax.swing.JComboBox();
        CancelarCadastroAnimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_idAnimal.setText("ID");

        Label_NomeAnimal.setText("Nome");

        Label_RacaAnimal.setText("Raça");

        NomeCadastroAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeCadastroAnimalActionPerformed(evt);
            }
        });

        Label_TipoAnimal.setText("Tipo");

        Label_NascAnimal.setText("Nascimento");

        try {
            Nasc_CadastroAnimal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        SalvarCadastroAnimal.setText("Salvar");
        SalvarCadastroAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarCadastroAnimalActionPerformed(evt);
            }
        });

        Combo_TipoAnimal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Canino", "Felino" }));

        CancelarCadastroAnimal.setText("Cancelar");
        CancelarCadastroAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarCadastroAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Label_idAnimal)
                        .addGap(26, 26, 26)
                        .addComponent(IDCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(SalvarCadastroAnimal)
                                .addGap(27, 27, 27)
                                .addComponent(CancelarCadastroAnimal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label_NomeAnimal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NomeCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 216, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_RacaAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RacaCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_TipoAnimal)
                        .addGap(18, 18, 18)
                        .addComponent(Combo_TipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_NascAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Nasc_CadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_idAnimal)
                    .addComponent(IDCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_NascAnimal)
                    .addComponent(Nasc_CadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_TipoAnimal)
                    .addComponent(Combo_TipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label_RacaAnimal)
                    .addComponent(RacaCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_NomeAnimal)
                    .addComponent(NomeCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarCadastroAnimal)
                    .addComponent(CancelarCadastroAnimal))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarCadastroAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarCadastroAnimalActionPerformed
        Animal a = new Animal();
        
        a.setId_Animal(Integer.parseInt(IDCadastroAnimal.getText()));
        /*a.setNascimento(Nasc_CadastroAnimal.getText()); */
        String tipo_a = Combo_TipoAnimal.getSelectedItem()+"";
        a.setTipo(tipo_a);
        a.setRaca(RacaCadastroAnimal.getText());
        a.setNome(NomeCadastroAnimal.getText());
        
        
        
        /*String id_a = IDCadastroAnimal.getText();
        int id_a_int = Integer.parseInt(id_a);
        a.setId_Animal(id_a_int);
        String tipo_a = Combo_TipoAnimal.getSelectedItem()+"";
        a.setTipo(tipo_a); */
        
        if ((IDCadastroAnimal.getText().isEmpty())
                || (Combo_TipoAnimal.getSelectedIndex() == 0 )) {
        
        JOptionPane.showMessageDialog(null, "Todos os Campos precisam ser preenchidos");
        }
        else{
            ControllerAnimal ca = new ControllerAnimal();
            try{
                System.out.println("Tentando Gravar no BD");
                
                ca.salvar(a.getId_Animal(), a.getNascimento(), a.getTipo(), a.getRaca(), a.getNome());
                System.out.println("Gravado no BD com Sucesso");
                
                JOptionPane.showMessageDialog(null, "Salvo com Sucesso!");
            } catch (SQLException e) {
                e.printStackTrace(); 
            }finally{
                System.out.println("Fim da Inserção");
                IDCadastroAnimal.setText("");
                
            }
        }
    }//GEN-LAST:event_SalvarCadastroAnimalActionPerformed

    private void CancelarCadastroAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarCadastroAnimalActionPerformed
        IDCadastroAnimal.setText("");
        NomeCadastroAnimal.setText("");
        RacaCadastroAnimal.setText("");
        Nasc_CadastroAnimal.setText("");
    }//GEN-LAST:event_CancelarCadastroAnimalActionPerformed

    private void NomeCadastroAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCadastroAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeCadastroAnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarCadastroAnimal;
    private javax.swing.JComboBox Combo_TipoAnimal;
    private javax.swing.JTextField IDCadastroAnimal;
    private javax.swing.JLabel Label_NascAnimal;
    private javax.swing.JLabel Label_NomeAnimal;
    private javax.swing.JLabel Label_RacaAnimal;
    private javax.swing.JLabel Label_TipoAnimal;
    private javax.swing.JLabel Label_idAnimal;
    private javax.swing.JFormattedTextField Nasc_CadastroAnimal;
    private javax.swing.JTextField NomeCadastroAnimal;
    private javax.swing.JTextField RacaCadastroAnimal;
    private javax.swing.JButton SalvarCadastroAnimal;
    // End of variables declaration//GEN-END:variables
}
